GET http://localhost:8080/api/products
accept: application/json
###

GET http://localhost:8080/api/products/3
accept: application/json

###
GET http://localhost:8080/api/products?low=100&high=5000
accept: application/json

###

GET http://localhost:8080/api/products?low=100&high=5000
accept: application/json

###

POST http://localhost:8080/api/products
accept: application/json
content-type: application/json
{
    "name": "OnePlus14",
    "price": 87341.11,
    "quantity": 100
}



