GET http://localhost:8080/api/products
accept: application/json
###

GET http://localhost:8080/api/products/3
accept: application/json

###
GET http://localhost:8080/api/products?low=100&high=5000
accept: application/json

###

GET http://localhost:8080/api/products?low=100&high=5000
accept: application/json

###

POST http://localhost:8080/api/products
accept: application/json
content-type: application/json

{ "name": "Reynold", "price": 120.10, "quantity": 100 }

###


PATCH http://localhost:8080/api/employees/1
Content-Type: application/json-patch+json
Accept: application/json
[
                        {"op":"replace", "path": "/title" , "value" : "Team Lead"},
                        {"op" : "add" , "path": "/communication/phone", "value": "1234567890"},
                        {"op": "remove", "path": "/communication/email"},
                        {"op" : "add" , "path": "/skills/1", "value": "AWS"}
                    ]


###
POST http://localhost:8080/api/products
accept: application/json
content-type: application/json

{ "name": "nn", "price": 8, "quantity": 0 }

###
GET http://localhost:8080/api/products/etag/3
accept: application/json

###
GET http://localhost:8080/api/products/etag/3
If-None-Match: "-645019294"
accept: application/json

###
GET http://localhost:8080/api/products/cache/1
accept: application/json

###
GET http://localhost:8080/api/products/hateoas/1
accept: application/json