server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: school-service
  datasource:
    url: jdbc:mysql://localhost:3306/SYNC_SPRING?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: Welcome123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
