spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: c603953a930ac733c5e7
            clientSecret: 9f8b8d273fd0a5b845a063d3c870b6a64ebd1e51
#          google:
#            clientId: ${google-app-client-id}
#            clientSecret: ${google-app-client-id}