package com.adobe.prj.service;

import java.util.List;
import java.util.Optional;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.adobe.prj.dao.OrderDao;
import com.adobe.prj.dao.ProductDao;
import com.adobe.prj.entity.Item;
import com.adobe.prj.entity.Order;
import com.adobe.prj.entity.Product;
import com.sun.xml.txw2.IllegalAnnotationException;

@Service
public class OrderService {
	// wires implmentation class for this interface, generated by data jpa
	@Autowired
	private ProductDao productDao;
	
	@Autowired
	private OrderDao orderDao;
	
	@Transactional
	public void modifyProduct() {
		 
		Product p = productDao.findById(3).get();
		p.setQuantity(p.getQuantity() - 23);
		System.out.println(p);
	}
	/* 
	 {
	 	"customer": {"email", "a@adobe.com"},
	 	"items": [
	 		{"product": {"id": 4},"quantity": 3},
	 		{"product": {"id": 1},"quantity": 2}
	 	]
	 }
	*/
	@Transactional
	public Order placeOrder(Order o) {
		double total = 0.0;
		List<Item> items = o.getItems();
		for(Item i : items) {
			Product p = productDao.findById(i.getProduct().getId()).get();
			if((p.getQuantity() - i.getQuantity()) <= 0) {
				throw new IllegalAnnotationException("Product " + p.getName() + " not is stock!!!");
			}
			p.setQuantity(p.getQuantity() - i.getQuantity()); // Dirty Checking ==> update SQL
			i.setAmount(p.getPrice() * i.getQuantity());
			total += i.getAmount();
		}
		o.setTotal(total);
		return orderDao.save(o); // cascade saves "items" also
	}
	
	public List<Order> getOrders() {
	  List<Order> orders = orderDao.findAll();
	  System.out.println("Has Items been fetched!!!");
	  return orders;
	}
	
	
	public Product insertProduct(Product p) {
		return productDao.save(p);
	}
	
	public List<Product> getByRange(double low, double high) {
		return productDao.getByRange(low, high);
	}
	
	public Product updatePrice(int id, double price) {
		productDao.updateProduct(id, price);
		return this.getProductById(id);
	}
	
	public List<Product> getProducts() {
		return productDao.findAll();
	}
	
	public Product getProductById(int id) {
		Optional<Product> opt = productDao.findById(id);
		if(opt.isPresent()) {
			return opt.get();
		} else {
			return null;
		}
		
	}
}
