spring.application.name=security-demo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/SPRING_SECURE?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Welcome123

# triggers schema.sql followed by data.sql
spring.sql.init.mode=always

# details for EntityManagerFactory
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
