eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 1234
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/schools/**
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: students
#        uri: http://localhost:8090
#        predicates:
#        - Path=/api/students/**
#      - id: schools
#        uri: http://localhost:8070
#        predicates:
#        - Path=/api/schools/**