spring.application.name=vehicle-rental

#server.port=9999


# create database NCG_RENTAL;
spring.datasource.url=jdbc:mysql://localhost:3306/CISCO_RENTAL?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Welcome123
spring.datasource.hikari.maximum-pool-size=50


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=averylengthysaltvaluetobeusedtogenerateajwttokenitneedstobeminimumof256characters
