package com.cisco.shopapp.repo;

import com.cisco.shopapp.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

// implementation classes are generated by Spring Data JPA
public interface CustomerRepo extends JpaRepository<Customer, String> {

    // JP-QL Projections
    // select * from customers where lname= ?
    List<Customer> findByLastName(String name);
    // select * from customers where fname = ? OR lname= ?
    List<Customer> findByFirstNameOrLastName(String fname, String lname );

    // select * from customers where fname = %?%
    List<Customer> findByFirstNameContains(String name);
}
