package com.cisco.shopapp.repo;

import com.cisco.shopapp.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;

// implementation classes are generated by Spring Data JPA
public interface CustomerRepo extends JpaRepository<Customer, String> {
}
