package com.cisco.shopapp.repo;

import com.cisco.shopapp.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

// implementation classes are generated by Spring Data JPA
public interface ProductRepo extends JpaRepository<Product, Integer> {
    // JP-QL Projections

    // select * from products where price between ? and ?
    List<Product> findByPriceBetween(double low, double high);
    List<Product> findByPriceGreaterThan(double price);

    @Modifying
//    @Query(value = "update products set price = :pr where id = :id", nativeQuery=true)
    @Query("update Product set price = :pr where id = :id")
    void modifyProductPrice(@Param("id") int id, @Param("pr") double price);

}
