package com.cisco.shopapp.repo;

import com.cisco.shopapp.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;

// implementation classes are generated by Spring Data JPA
public interface ProductRepo extends JpaRepository<Product, Integer> {
}
