spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  data:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
---
#axon:
#  axonserver:
#    servers: 192.168.0.103:8124
#  serializer:
#    general: jackson
#    events: jackson
#    messages: jackson